#!/bin/bash

# 1. Check and extract script parameters
if [ -z "$1" ]; then
    echo "Please provide the name of the workspace project directory you want to activate."
    echo "Activate project in $WORDSLAB_WORKSPACE/myprojectdir : source activate-workspace-project myprojectdir"
    exit 1
else
    dir_name=$1
fi
if [ ! -d "$WORDSLAB_WORKSPACE/$dir_name" ]; then
    echo "Directory $WORDSLAB_WORKSPACE/$dir_name not found: please choose another project name"
    exit 1
fi

# 2. Navigate to the project directory
cd $WORDSLAB_WORKSPACE/$dir_name

# 3. Activate the virtual environment
echo "Activating the python environment for project: $WORDSLAB_WORKSPACE/$dir_name"
source .venv/bin/activate