[project]
name = "docling-env"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
# https://github.com/docling-project/docling-serve/blob/v1.3.1/pyproject.toml
    "docling==2.92.0", # Pin the version of Docling to ensure reproducibility
    "docling-serve[ui]==1.17.0",
]

[project.optional-dependencies]
cpu = [
  "torch==2.11.0",
  "torchvision==0.26.0",
  "torchaudio==2.11.0"
]
cuda = [
  "torch==2.11.0",
  "torchvision==0.26.0",
  "torchaudio==2.11.0"
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cuda" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu130", extra = "cuda" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu130", extra = "cuda" },
]
torchaudio = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu130", extra = "cuda" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true